version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goyo_postgres
    environment:
      POSTGRES_USER: goyo_user
      POSTGRES_PASSWORD: goyo_pass
      POSTGRES_DB: goyo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: goyo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: goyo_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

volumes:
  postgres_data:
  redis_data:
  mosquitto_data: